# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title kernel density visualization in C++
#' @name kdvCpp
#' @param args arguments for kdv
#' @return the kdv result
#' @keywords internal
kdvCpp <- function(args) {
    .Call('_Rlibkdv_kdvCpp', PACKAGE = 'Rlibkdv', args)
}

